# Generated by Django 5.0.7 on 2024-07-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcuser',
            old_name='permisions',
            new_name='permissions',
        ),
    ]
