# Generated by Django 5.0.7 on 2024-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/'),
        ),
    ]
