# Generated by Django 5.2 on 2025-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rcuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='rcuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
