# Generated by Django 5.2 on 2025-06-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_permissionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcuser',
            name='signed_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcuser',
            name='signed_url_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
