# Generated by Django 5.2 on 2025-07-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissionrequest',
            unique_together={('permission', 'user')},
        ),
    ]
