# Generated by Django 5.0.7 on 2024-08-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_closet_project_something_type_delete_shelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='something',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_somethings', to='store.project'),
        ),
    ]
