# Generated by Django 5.0.7 on 2024-08-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_something_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='number_of_some_things',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_some_things',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='number_of_some_things',
            field=models.IntegerField(default=0),
        ),
    ]
