# Generated by Django 5.0.7 on 2024-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_closet_number_of_some_things_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='something',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/'),
        ),
    ]
