# Generated by Django 5.2 on 2025-06-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_project_image_something_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='something',
            name='image',
        ),
        migrations.CreateModel(
            name='ClosetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/')),
                ('signed_url', models.TextField(blank=True, null=True)),
                ('signed_url_generated_at', models.DateTimeField(blank=True, null=True)),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyImages', to='store.closet')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/')),
                ('signed_url', models.TextField(blank=True, null=True)),
                ('signed_url_generated_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyImages', to='store.project')),
            ],
        ),
        migrations.CreateModel(
            name='SomeThingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/')),
                ('signed_url', models.TextField(blank=True, null=True)),
                ('signed_url_generated_at', models.DateTimeField(blank=True, null=True)),
                ('someThing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyImages', to='store.something')),
            ],
        ),
    ]
