# Generated by Django 5.2 on 2025-08-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_project_image_remove_something_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='something',
            name='borrowed',
        ),
    ]
