# Generated by Django 5.2 on 2025-08-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_something_borrowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='something',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='something',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
