# Generated by Django 5.2 on 2025-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_something_options_something_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='number_of_some_things',
        ),
        migrations.RemoveField(
            model_name='type',
            name='number_of_some_things',
        ),
        migrations.AddField(
            model_name='closet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ClosetImage',
        ),
    ]
