# Generated by Django 5.2 on 2025-08-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_closet_number_of_some_things_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='number_of_some_things',
        ),
    ]
