# Generated by Django 5.0.7 on 2024-08-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
