# Generated by Django 5.0.7 on 2024-08-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
    ]
