# Generated by Django 5.0.7 on 2024-08-30 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_group_alter_mygroup_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='mymessages', to='chat.mygroup'),
        ),
        migrations.AlterField(
            model_name='mygroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='mygroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
