# Generated by Django 5.2 on 2025-07-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_groupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_contain_file',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('signed_url', models.TextField(blank=True, null=True)),
                ('signed_url_generated_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyFiles', to='chat.message')),
            ],
        ),
    ]
