# Generated by Django 5.2 on 2025-07-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_message_is_contain_file_messagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefile',
            name='origin_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
