# Generated by Django 5.0.7 on 2024-08-14 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_closet_number_of_some_things_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_user', to=settings.AUTH_USER_MODEL)),
                ('something', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_something', to='store.something')),
            ],
        ),
    ]
