# Generated by Django 5.0.7 on 2024-08-14 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_closet_number_of_some_things_and_more'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='something',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_something', to='store.something'),
        ),
    ]
