# Generated by Django 5.0.7 on 2024-08-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_closet_number_of_some_things_and_more'),
        ('utils', '0003_remove_borrow_person_alter_borrow_something_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='something',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrow_something', to='store.something'),
        ),
    ]
