# Generated by Django 5.0.7 on 2024-08-14 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_remove_borrow_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='person',
            field=models.ManyToManyField(related_name='borrow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
