# Generated by Django 5.2 on 2025-05-28 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_borrow_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='person',
            field=models.ManyToManyField(related_name='borrowed_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
