# Generated by Django 5.2 on 2025-05-28 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_project_image_something_image'),
        ('utils', '0007_alter_borrow_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='person',
            field=models.ManyToManyField(db_constraint=False, related_name='borrowed_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='something',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrow_something', to='store.something'),
        ),
    ]
