# Generated by Django 5.2 on 2025-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_post_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='signed_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='signed_url_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
