# Generated by Django 5.2 on 2025-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_alter_post_options_postimage_signed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='is_for_web_and_app',
            field=models.BooleanField(default=False),
        ),
    ]
