# Generated by Django 5.2 on 2025-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_remove_postimage_is_for_web_and_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
