# Generated by Django 5.2 on 2025-08-09 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_borrow_is_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='date_start',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='person',
        ),
        migrations.AddField(
            model_name='borrow',
            name='person',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
